### ISSUE TITLE
ver 1.12, ubuntu -> Error in findFileFormatStream: failed to read first 12 bytes of file

### ISSUE THREAD

**Issue by jmokoistinen** [zdenop/qt-box-editor#52]
When trying to open tif/box file pair from the editor
Error in findFileFormatStream: failed to read first 12 bytes of file
And the file does not open.

**Comment by jmokoistinen** [comment]
Also this occur sometimes
Error in fopenReadStream: file not found
Error in fileFormatIsTiff: stream not defined

**Comment by zdenop** [comment]
Please provide example files.

**Comment by jmokoistinen** [comment]
libtifiles-dev was missing

**Comment by patchworquill** [comment]
For future people who get here:

I was using `os.listdir()` to enumerate the files within a directory, but one of the cases I hadn't considered was that a **directory** within the results of `os.listdir()` was matching the naming pattern I was filtering on. 

Adding an additional condition as follows worked for me:
```python
for item in os.listdir():
    if "name" in item and os.path.isfile(item):
         # do stuff
```

The important thing to add is a condition that checks it is a file, and ideally it should check that it is an _image file_, because the error here is that the file being processed **_is not an image file_**
